version: '2.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: privacy-manager-verdaccio-memory
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
volumes:
  verdaccio:
    driver: local
