name: Docs
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          version: 18.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build docs
        working-directory: packages/docs
        run: yarn build

      
